# Generated by Django 5.2.8 on 2025-11-14 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalistaRetencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=100, unique=True)),
                ('razon_social', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='Activo', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EjecutivoRetencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('max_carga_renta', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('disponible_asignacion', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estado', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NivelAprobacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_nivel', models.CharField(max_length=100)),
                ('orden', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Circuito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_circuito', models.CharField(max_length=100)),
                ('tipo_servicio', models.CharField(blank=True, max_length=10, null=True)),
                ('estado', models.CharField(default='Activo', max_length=20)),
                ('renta_mensual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal_retenciones.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('asignado_automaticamente', models.BooleanField(default=False)),
                ('fecha_solicitud_baja', models.DateField(blank=True, null=True)),
                ('analista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal_retenciones.analistaretencion')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal_retenciones.cliente')),
                ('ejecutivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal_retenciones.ejecutivoretencion')),
                ('estado_actual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal_retenciones.estadoatencion')),
                ('nivel_aprobacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal_retenciones.nivelaprobacion')),
                ('usuario_creador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_view_menu', 'Puede ver el menú de inicio (requerido para login)'), ('can_create_solicitud', 'Puede acceder al formulario de Nueva Solicitud'), ('can_view_solicitud_list', 'Puede acceder a la lista de Solicitudes'), ('can_view_personal', 'Puede acceder a la lista de Personal Activo'), ('can_manage_personnel', 'Puede gestionar la asignación de personal a roles')],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('usuario_cambio', models.CharField(max_length=100)),
                ('estado_anterior', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='portal_retenciones.estadoatencion')),
                ('estado_nuevo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='portal_retenciones.estadoatencion')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal_retenciones.solicitud')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('ejecutivo_anterior', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_anterior', to='portal_retenciones.ejecutivoretencion')),
                ('ejecutivo_nuevo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_nuevo', to='portal_retenciones.ejecutivoretencion')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal_retenciones.solicitud')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('comentario', models.TextField()),
                ('fecha_comentario', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal_retenciones.solicitud')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudCircuito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asociacion', models.DateTimeField(auto_now_add=True)),
                ('circuito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal_retenciones.circuito')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal_retenciones.solicitud')),
            ],
            options={
                'unique_together': {('solicitud', 'circuito')},
            },
        ),
        migrations.AddField(
            model_name='solicitud',
            name='circuitos',
            field=models.ManyToManyField(through='portal_retenciones.SolicitudCircuito', to='portal_retenciones.circuito'),
        ),
    ]
