# Generated by Django 5.2.8 on 2025-11-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_retenciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionAsignacion',
            fields=[
                ('clave', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('valor', models.IntegerField(default=0)),
            ],
        ),
    ]
